sudo: required
services:
  - docker

before_install:
  - docker build -t brajarajan/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true brajarajan/docker-react npm run test -- --coverage
  #Additionally, you may want to set the following property to the top of your .travis.yml file:
  
language: generic 